import numpy as np
import itertools

##### options of target state #####
def tensor_T(n):
    """ This function returns the tensor product of n T gates 
    as a numpy 1d-array
    
    Args:
        n (int): number of gates to tensor
    
    Returns:
        (complex) numpy 1d-array of length 2**n
    """
    return np.array([1.0]*(2**n-1)+[np.exp(1j*np.pi/4)])

def multi_RZ(theta,n):
    """ This function returns the C^(n-1)-RZ(theta) on n qubits 
    as a numpy 1d-array 
    
    Args:
        theta (float): angle of the RZ gate
        n (int): number of qubits the gate acts on

    Returns:
        (complex) numpy 1d-array of length 2**n """
    
    return np.array([1.0]*(2**n-1)+[np.exp(1j*theta)])

def multi_CZ(n):
    """ This function returns the C^(n-1)-Z gate on n qubits 
    as a numpy 1d-array 
    
    Args:
        n (int): number of qubits the gate acts on
    
    Returns:
        (float) numpy 1d-array of length 2**n """
    
    out = np.array([1.0]*(2**n-1)+[-1.0])
    if n<=1:
        out = 0
        print("Warning: multi_CZ({}) is not defined".format(n))
    return out

def multi_CS(n):
    """ This function returns the C^(n-1)-S gate on n qubits 
    as a numpy 1d-array
    
    Args:
        n (int): number of qubits the gate acts on
    
    Returns:
        (complex) numpy 1d-array of length 2**n """
    
    out = np.array([1.0]*(2**n-1)+[1j])
    if n<=1:
        out = 0
        print("Warning: multi_CS({}) is not defined".format(n))
    return out

##### auxiliary functions for generating decompositions elements #####
def gen_symmetric_Rs(n):
    """ This function returns a list of all symmetric matrices R of size n x n. 
    They are in one-to-one correspondence with the elements of the diagonal Clifford group
    on n qubits in the quocient space Clifford(n)/Paulis(n).
    
    Args:
        n (int): size of the returned squared matrices
    
    Returns:
        list of (int) numpy arrays of shape (n,n) """
    
    Rs=[]
    bs=list(itertools.product([0,1], repeat=n)) # list of possible bitstrings of length n
    os=list(itertools.product([0,1], repeat=(sum([n-1-i for i in range(n-1)])))) # same for upper off-diagonal number of elements
    for b in bs:
        for o in os:
            R=np.zeros((n,n),dtype=np.int8)
            for i in range(n):
                R[i,i]=b[i] # a 1 here corresponds to a phase gate on qubit i
                for j in range(n-1-i):
                    if o[sum([n-k-1 for k in range(i)])+j]==1:
                        R[i,i+j+1]=1 # a 1 here corresponds to a CZ gate between the indexed qubits
                        R[i+j+1,i]=1
            Rs.append(R.copy())
    return Rs

def gen_symmetric_Rs_for_CZS(n):
    """ This function returns a list of all symmetric matrices R of size n x n with zeros on the diagonal. 
    They are in one-to-one correspondence with the elements of the diagonal Clifford group
    on n qubits in the quocient space Clifford(n)/Paulis(n) that are generated by CZ gates only.
    
    Args:
        n (int): size of the returned squared matrices
    
    Returns:
        list of (int) numpy arrays of shape (n,n) """
    
    Rs=[]
    os=list(itertools.product([0,1], repeat=(sum([n-1-i for i in range(n-1)]))))
    for o in os:
        R=np.zeros((n,n),dtype=np.int8)
        for i in range(n):
            for j in range(n-1-i):
                if o[sum([n-k-1 for k in range(i)])+j]==1:
                    R[i,i+j+1]=1
                    R[i+j+1,i]=1
        Rs.append(R.copy())
    return Rs

def diagonal_Clifford_from_R(R):
    """ This function returns the diagonal Clifford operator corresponding to a given symmetric matrix R.
    It returns the operator as a numpy 1d-array, i.e. only the diagonal elements are stored.
    
    Args:
        R (int) numpy array of shape (n,n): symmetric matrix defining the Clifford operator
    
    Returns:
        (complex) numpy 1d-array of length 2**n """
    
    n=R.shape[0]
    out=np.zeros(2**n, dtype=np.complex64)
    vs=list(itertools.product([0,1], repeat=n))
    for v in vs:
        index=0
        for i in range(n):
            index+=v[i]*2**(n-1-i)
        out[index]=1j**(np.array(v)@R@np.array(v))
    return out

def diagonal_paulis(n):
    """ This function returns a list of all n-qubit Pauli Z operators.

    Args:
        n (int): number of qubits the operators act on

    Returns:
        list of (int) numpy 1d-arrays of length 2**n """
    
    diag_p=[]
    Z=np.array([1,-1], dtype=np.int8)
    Id=np.array([1,1], dtype=np.int8)
    bs=list(itertools.product([0,1], repeat=n))
    for b in bs:
        out=np.array(1, dtype=np.int8)
        for i in range(n):
            if b[i]==1:
                out=np.kron(out,Z)
            else:
                out=np.kron(out,Id)
        diag_p.append(out.copy())
    return diag_p

##### main function for solving the optimization problem #####
import gurobipy as gp
from gurobipy import GRB

def sext_diagonals(A,target,params={'Threads':1, 'FeasibilityTol':1e-9}, only_reals=False, write_to_mps=False):
    """ This function computes the stabilizer extent of a diagonal target state given a matrix A whose columns are the 
    decomposition elements to be used in its optimization. It uses Gurobi as solver, and therefore requires a valid Gurobi license.
    
    Args:
        A: numpy 2d array of shape (2**n, 2**(m+1)) if only_reals=False, else of shape (2**n, 2**m), where n is the number of qubits
            involved and m is the number of elements in the decomposition set. The first half of the columns of A correspond to 
            the real parts of them, say A_r, while the second half to the imaginary parts, say A_i, such that A=numpy.hstack((A_r,A_i));
        target: numpy 1d array of shape (2**n,) corresponding to the target state whose stabilizer extent is to be computed;
        params: dictionary of parameters to be passed to Gurobi. By default we set it to use a single thread to avoid memory overload 
            and maximum feasibility tolerance of 1e-9;
        only_reals: boolean, if True the optimization is performed over real variables only."""
    
    n=int(np.log2(target.shape[0])) # number of qubits

    # number of elements
    if only_reals:
        cardinality=(A.shape[1])
    else:
        cardinality=(A.shape[1]//2)

    # setting the target, as a vector u
    if only_reals:
        u=target
    else:
        u=np.concatenate((np.real(target),np.imag(target)))

    #defining the model
    m=gp.Model() # initialize

    # variables first
    a=m.addMVar(cardinality, lb=-GRB.INFINITY, name="a")
    if not only_reals:
        b=m.addMVar(cardinality, lb=-GRB.INFINITY, name="b")
    t=m.addMVar(cardinality, name="t")

    # now constraints
    if only_reals:
        m.addConstr(a<=t, name="a_leq_t")
        m.addConstr(-t<=a, name="minus_t_leq_a")
        m.addConstr(A@a==u, "A_x_a_equal_u")
    else:
        m.addConstr(a*a+b*b<=t*t, name="a2_plus_b2_leq_t2")
        m.addConstr(A[:,:A.shape[1]//2]@a+(-A[:,A.shape[1]//2:])@b==u[:2**n], name="real_A_x_ab_equal_u")
        m.addConstr(A[:,:A.shape[1]//2]@b+A[:,A.shape[1]//2:]@a==u[2**n:],name="imag_A_x_ab_equal_u")

    # setting the objective
    obj=gp.quicksum(t)
    m.setObjective(obj)

    # setting input parameters
    if len(params) != 0:
        for p in params:
            m.setParam(p, params[p])

    # required step of updating the model before optimization
    m.update()
    if write_to_mps:
        m.write("model.mps") # write the model to a file in mps format

    # optimization itself
    m.optimize()

    # outputs
    if m.status != GRB.OPTIMAL:
        print("Warning: the optimization did not end up with an optimal solution, status code {}".format(m.status))
    else:
        if only_reals:
            out=(m.ObjVal**2, a.X)
        else:
            out=(m.ObjVal**2, a.X+1j*b.X)

    return out

##### auxiliary functions for twirling with permutation group #####
from itertools import permutations, product

def permutations_matrices(n):
    """ This function returns a list of all n-qubit permutation matrices.
    
    Args:
        n (int): number of qubits the operators act on
    
    Returns:
        list of (int) numpy 2d-arrays of shape (2**n,2**n) """

    bits_permutations = list(permutations(range(1, n+1)))

    out=[]
    for sigma in bits_permutations:
        P = np.zeros((2**n, 2**n), dtype=np.int32)
        # Iterate over all basis states |i_1...i_n⟩
        for bits in product([0, 1], repeat=n):
            original_idx = int(''.join(map(str, bits)), 2)  # Binary to decimal
            permuted_bits = [bits[sigma[k] - 1] for k in range(n)]  # Apply sigma (1-based)
            permuted_idx = int(''.join(map(str, permuted_bits)), 2)
            P[permuted_idx, original_idx] = 1
        out.append(P.copy())
    return out

from numba import jit, prange

@jit(parallel=True, nopython=True)
def matmul_manual(A, B):
    """Manually multiply two int32 matrices A and B.
    
    Args:
        A: numpy 2d array of shape (n, m)
        B: numpy 2d array of shape (m, p)
    
    Returns:
        numpy 2d array of shape (n, p) resulting from A @ B executed "manually". """

    n, m = A.shape
    m2, p = B.shape
    assert m == m2, "Incompatible dimensions for matrix multiplication"
    result = np.zeros((n, p), dtype=np.int32) # Use int32 to avoid overflow
    for i in prange(n):
        for j in prange(p):
            for k in prange(m):
                result[i, j] += int(A[i, k]) * int(B[k, j])
    return result

@jit(parallel=True, nopython=True)
def twirl_permutations(M,n,permutations_elements):
    """ This functions computes the twirling of a matrix M by all n-qubit permutation matrices.
    
    Args:
        M: numpy 2d array of shape (2**n, 2**n)
        n (int): number of qubits the operators act on
        permutations_elements: list of all permutation matrices corresponding to n
    
    Returns:
        numpy 2d array of shape (2**n, 2**n) resulting from the twirling of M by all n-qubit permutation matrices. """

    out = np.zeros((2**n,2**n),dtype=np.int32)
    for i in prange(len(permutations_elements)):
        sigma = permutations_elements[i]
        out = out + matmul_manual(matmul_manual(sigma,M),sigma.T)
    return (1/len(permutations_elements))*out

@jit(parallel=True, nopython=True)
def twirled_A(A,n,permutations_elements):
    """ This functions computes the twirling of all the elements encoded in the columns of A by all n-qubit permutation matrices.
    
    Args:
        A: numpy 2d array of shape (2**n, m)
        n (int): number of qubits the operators act on
        permutations_elements: list of all permutation matrices corresponding to n
        
    Returns:
        numpy 2d array of shape (2**n, m) resulting from the twirling of all the elements encoded in the columns of A."""
    
    out=np.empty(A.shape,dtype=float)
    for i in prange(A.shape[1]):
        out[:,i]=np.diag(twirl_permutations(np.diag(A[:,i]),n,permutations_elements))
    return out

##### auxiliary functions for collecting non-equivalent diagonals by CZ category #####
def Rs_with_phases_from_non_equiv_graphs(adjacency_matrices):
    """ This function returns a list of all resulting symmetric R matrices after including all possible
    phases configurations to all adjacency matrices corresponding to non-equivalent graphs by permutation. 
    For each adjacency matrix, it appends elements with added diagonal parts corresponding to each phase 
    configuration.
    
    Args:
        adjacency_matrices: list of nxn matrices corresponding to non-equivalent graphs as adjacency matrices
        
    Returns:
        list of symmetric R matrices"""

    # number of qubits/vertices
    n=adjacency_matrices[0].shape[0]

    # possible phases
    bs=list(product([0,1], repeat=n))

    # initialize output list
    Rs=[]

    for b in bs:
        for G in adjacency_matrices:
            Rs.append(G+np.diag(b))
    return Rs

@jit(parallel=True, nopython=True)
def remove_equivalent_diagonals(all_diag, permutations_elements, only_reals=False):
    """ This function removes equivalent diagonal Cliffords by some permutation conjugation from a given 
    collection of them. 
    
    Args:
        all_diag: numpy 2d-array whose columns are diagonal Cliffords to be filtered, in the form of numpy.hstack((A_r,A_i)), 
            with A_r the real part of those diagonals and A_i the imaginary one, respectively shifted.
        permutations_elements: list of all permutation matrices corresponding to number of qubits the diagonal Ciffords act on 
        only_reals: boolean, adjust the function in the case of real diagonals only
        
    Returns:
        numpy 2d-array with non-equivalent diagonal Cliffords only, following the same input split between real and imaginary part"""

    mask = np.ones(all_diag.shape[1], dtype=np.bool_)  # Mask to keep track of which diagonals to keep
    if only_reals:
        cardinality=all_diag.shape[1]
    else:
        cardinality=all_diag.shape[1]//2
    for i in range(cardinality):
        if not mask[i]:
            continue
        d_real = all_diag[:,i]
        if not only_reals:
            d_imag = all_diag[:,i + cardinality]
        for p in permutations_elements:
            pdpT_real = np.diag(matmul_manual(matmul_manual(p,np.diag(d_real)),p.T))
            if not only_reals:
                pdpT_imag = np.diag(matmul_manual(matmul_manual(p,np.diag(d_imag)),p.T))
            for j in prange(i + 1, cardinality):
                if not mask[j]:
                    continue
                if only_reals:
                    if (pdpT_real == all_diag[:,j]).all():
                        mask[j] = False  # Mark as duplicate
                else:
                    if (pdpT_real == all_diag[:,j]).all() and (pdpT_imag == all_diag[:,j+cardinality]).all():
                        mask[j] = False  # Mark as duplicate
                        mask[j + cardinality] = False

    # Return only the diagonals that are not marked as duplicates
    return [all_diag[:,i] for i in range(all_diag.shape[1]) if mask[i]]